### ISSUE TITLE
Deleting video upon button Click

### ISSUE THREAD

**Issue by YuhBoh** [PrimeAcademy/citrine-syllabus#3]
## Description

* What do you want your code to do?
I want a link to a video to be deleted and update the DOM when button is pressed.

* What is your code actually doing?
The video isn't deleted until I refresh the page
---

## Screenshots / Code Snippets

* Include a screenshot of the problem, and/or copy-paste relevant code and error messages.

* Note that you can drag-and-drop images into the github editor!
![image](https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/bc9b4961-7a55-4e0a-90b1-c526170545a5)

---

## What did you try? Who did you ask?

* Briefly describe your debug process. What did you do to isolate the issue?
    * Remember to "bubble up" your questions. Start with Google, then your pod, and then your cohort.  
 I asked for pod cohorts and also asked Luis for help as well. I tried debugging some issues and looked over some class notes.

---

## When was the last time you took a break?

* Like, a real break. Bugs have this amazing way of just disappearing into nothingness when you take some time to clear your head. Go for a walk or something!

1PM PST

**Comment by aharasymiw** [comment]
We can talk more tomorrow, but I think it's likely going to be a very similar flow to adding a video.

![image](https://github.com/PrimeAcademy/citrine-syllabus/assets/9385810/87a5d047-9f9f-4b1e-ab04-6f8e52284903)


The only difference is, instead of the first saga in the diagram being a "POST", it'll be a DELETE.

So, once your code sends the delete to your server, it will wait for an answer.  On an "OK" answer, you want to call your "GET" saga again, to fetch all the URLS (the full list, that should now be missing the deleted one), and update redux with the new list.
