### ISSUE TITLE
updating rows with foreign keys

### ISSUE THREAD

**Issue by YuhBoh** [PrimeAcademy/citrine-syllabus#5]
## Description

* What do you want your code to do?
I want to update the id column value.

* What is your code actually doing?
Not sure, I'm still testing different clauses.

---

## Screenshots / Code Snippets

![image](https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/b9e08e5f-0b20-4ecf-9cee-29eb533642ce)

---

## What did you try? Who did you ask?

I tried using DELETE; looked up SQL commands; asking for help in pod/personally/citrine.

---

## When was the last time you took a break?

11AM PST

**Comment by aharasymiw** [comment]
Sometimes, you can't just delete a row from a table.
Say, you had a table called users, and you wanted to delete one user (a row).
If you have another table (say, "videos"), that has a column for user_id, that's a foreign key pointing to the users table, you can't delete the the user, without first deleting the row in "videos" that points to the user.

SQL works this way, to prevent you from deleting things that other things point to or depend on.

Otherwise, you'd have "videos" pointing to a "user" that doesn't exist!

So, you have two ways to deal with this:
First, you delete all videos with a foreign key that matches the user id, then you delete the user.

Or, you can set up your tables when you create them, to take care of this for you.
You can look into "on delete cascade" to see how to do this.

**Comment by aharasymiw** [comment]
https://www.beekeeperstudio.io/blog/postgres-delete-cascade-guide
